### PR TITLE
fix(views): remove unused defaultModel declaration in model-picker

### PR DESCRIPTION
**Pull request by james-heidi**
## What does this PR do?

Removes a now-unused `defaultModel` `useMemo` declaration in `packages/views/agents/components/inspector/model-picker.tsx` that was orphaned by #1875. Restores `tsc --noEmit` (and CI) to green.

## Related Issue

Caused by #1875. Surfaced as a CI failure on #1880; fixing here unblocks both `main` and any open PR that gets the merged tree.

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature
- [ ] Refactor / code improvement (no behavior change)
- [ ] Documentation update
- [ ] Tests
- [ ] CI / infrastructure

## Changes Made

- `packages/views/agents/components/inspector/model-picker.tsx` — drop the orphaned `const defaultModel = useMemo(...)`. The sibling change in #1875 already deleted the declaration in `model-dropdown.tsx`; this is the missing half. Updated the adjacent comment so it no longer references the removed binding.

## How to Test

```bash
pnpm install
pnpm --filter @multica/views typecheck
```

Should exit cleanly. Before this change it fails with:

```
agents/components/inspector/model-picker.tsx(50,9): error TS6133: 'defaultModel' is declared but its value is never read.
```

No runtime behavior change — `defaultModel` was already unused after #1875.

## Checklist

- [x] I have included a thinking path that traces from project context to this change
- [x] I have run tests locally and they pass (`pnpm --filter @multica/views typecheck` clean)
- [ ] I have added or updated tests where applicable (N/A — pure dead-code removal)
- [ ] If this change affects the UI, I have included before/after screenshots (N/A — no UI change)
- [ ] I have updated relevant documentation to reflect my changes (N/A)
- [x] I have considered and documented any risks above
- [x] I will address all reviewer comments before requesting merge

## AI Disclosure

**AI tool used:** Claude Code (Opus 4.7).

**Prompt / approach:** Diagnosed CI failure on #1880, traced the unused-variable error to commit 55b7e2e9 which removed the consumer (`triggerLabel`) but left the declaration. Removed the declaration and refreshed the surrounding comment.

## Screenshots (optional)

N/A.

### CODE REVIEW

**Comment by james-heidi** [comment]
Superseded by #1878 — Multica Eve landed the same one-line removal (with a slightly tighter comment) at 12:35 UTC, before this PR could get a maintainer review. Closing to avoid the now-redundant conflict; nothing to merge.

Side effect: the take-command PR #1880 was conflicting on the same lines because james-heidi/main hadn't picked up #1878 yet. I've merged upstream/main into james-heidi/main (taking the upstream comment wording), pushed the merge, and #1880 now reports MERGEABLE.
