### PR TITLE
fix(issues): allow verified autopilot child assignment (MUL-6161)

### LINKED ISSUE #6941: [Bug]: Verified autopilot leader cannot create a backlog child assigned to a private agent
## What happened?

An unattributed (`originator_user_id = NULL`) leader task dispatched by a member-created autopilot can `@mention` a private worker owned by that autopilot creator, because the comment path restores the creator's invocation authority from verified task/issue lineage (the behavior added by #5512).

The same verified leader task cannot create a child issue assigned to that same private worker. `POST /api/issues` returns:

```json
{"error":"cannot assign to private agent"}
```

This also fails when the new child has `status: "backlog"`. Backlog assignment is explicitly a parking operation and does not enqueue a run, so the rejection cannot be explained as protection against an immediate execution.

I am **not** requesting a blanket A2A/private-agent bypass. The expected admission is limited to the same creator-owned target and the same server-verified autopilot lineage already accepted by the comment delegation path. Missing, mismatched, cross-issue, or unauthorized lineage should continue to fail closed.

## Steps to reproduce

Tested directly against upstream `main` at [`9ba3a8bdf26864f41fcfa04bdc83d6d3cced0ec9`](https://github.com/multica-ai/multica/commit/9ba3a8bdf26864f41fcfa04bdc83d6d3cced0ec9), with a fresh migrated `pgvector/pgvector:pg17` database.

Add this temporary regression test under `server/internal/handler`:

```go
package handler

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestReproAutopilotLeaderCreatesBacklogChildAssignedToPrivateAgent(t *testing.T) {
	if testHandler == nil || testPool == nil {
		t.Skip("database not available")
	}

	workerID, ownerID, _ := privateAgentTestFixture(t)
	fx := newAutopilotDelegationFixture(t, workerID, ownerID, "autopilot")
	parentIssueID := uuidToString(fx.Issue.ID)

	w := httptest.NewRecorder()
	r := newRequest("POST", "/api/issues?workspace_id="+testWorkspaceID, map[string]any{
		"title":           "repro: park private-agent handoff in backlog",
		"status":          "backlog",
		"priority":        "low",
		"assignee_type":   "agent",
		"assignee_id":     workerID,
		"parent_issue_id": parentIssueID,
		"allow_duplicate": true,
	})
	r.Header.Set("X-Agent-ID", fx.LeaderAgentID)
	r.Header.Set("X-Task-ID", fx.LeaderTaskID)
	testHandler.CreateIssue(w, r)

	if w.Code != http.StatusCreated {
		t.Fatalf("CreateIssue: expected 201 for a non-running backlog assignment, got %d: %s", w.Code, w.Body.String())
	}
}
```

Run the existing comment-delegation control:

```console
$ go test ./internal/handler -run '^TestCreateComment_AutopilotLeaderMentionEnqueuesPrivateWorker$' -count=1 -v
=== RUN   TestCreateComment_AutopilotLeaderMentionEnqueuesPrivateWorker
--- PASS: TestCreateComment_AutopilotLeaderMentionEnqueuesPrivateWorker (0.07s)
PASS
ok github.com/multica-ai/multica/server/internal/handler 0.211s
```

Run the reproduction:

```console
$ go test ./internal/handler -run '^TestReproAutopilotLeaderCreatesBacklogChildAssignedToPrivateAgent$' -count=1 -v
=== RUN   TestReproAutopilotLeaderCreatesBacklogChildAssignedToPrivateAgent
    issue_private_agent_assignment_repro_test.go:38: CreateIssue: expected 201 for a non-running backlog assignment, got 403: {"error":"cannot assign to private agent"}
--- FAIL: TestReproAutopilotLeaderCreatesBacklogChildAssignedToPrivateAgent (0.04s)
FAIL
```

## Expected behavior

The child issue is created with status `backlog` and the private worker as assignee. No worker task is enqueued until an allowed transition out of backlog.

The assignment gate should use a lineage-verified effective invocation authority consistent with the comment path. It should still deny unrelated unattributed agent tasks and autopilot creators that cannot invoke the target.

## Why this looks like an assignment-gate bug

1. The existing end-to-end test proves this exact autopilot leader/creator/private-worker relationship is authorized for an immediate `@mention` enqueue: [`autopilot_mention_authority_test.go#L276-L331`](https://github.com/multica-ai/multica/blob/9ba3a8bdf26864f41fcfa04bdc83d6d3cced0ec9/server/internal/handler/autopilot_mention_authority_test.go#L276-L331).
2. The comment path evaluates both the task's human originator and the lineage-verified autopilot creator authority: [`comment.go#L1906-L1915`](https://github.com/multica-ai/multica/blob/9ba3a8bdf26864f41fcfa04bdc83d6d3cced0ec9/server/internal/handler/comment.go#L1906-L1915).
3. `CreateIssue` invokes `validateAssigneePair` before it parses `parent_issue_id`: [`issue.go#L2482-L2515`](https://github.com/multica-ai/multica/blob/9ba3a8bdf26864f41fcfa04bdc83d6d3cced0ec9/server/internal/handler/issue.go#L2482-L2515).
4. `validateAssigneePair` passes only `invokeOriginatorFromRequest(...)` into `canInvokeAgent`: [`issue.go#L3211-L3225`](https://github.com/multica-ai/multica/blob/9ba3a8bdf26864f41fcfa04bdc83d6d3cced0ec9/server/internal/handler/issue.go#L3211-L3225). For an intentionally unattributed autopilot task, that resolver returns the NULL `originator_user_id` as an empty string: [`agent_access.go#L180-L200`](https://github.com/multica-ai/multica/blob/9ba3a8bdf26864f41fcfa04bdc83d6d3cced0ec9/server/internal/handler/agent_access.go#L180-L200).
5. The code already has a security-reviewed lineage resolver for this NULL-originator case, but it is wired to comment/quick-action paths rather than issue assignment: [`agent_access.go#L202-L283`](https://github.com/multica-ai/multica/blob/9ba3a8bdf26864f41fcfa04bdc83d6d3cced0ec9/server/internal/handler/agent_access.go#L202-L283).
6. Backlog assignment does not enqueue: [`issue_trigger.go#L99-L105`](https://github.com/multica-ai/multica/blob/9ba3a8bdf26864f41fcfa04bdc83d6d3cced0ec9/server/internal/service/issue_trigger.go#L99-L105) and [`issue.go#L607-L620`](https://github.com/multica-ai/multica/blob/9ba3a8bdf26864f41fcfa04bdc83d6d3cced0ec9/server/internal/service/issue.go#L607-L620).

## Suggested direction

Centralize the effective invocation-authority resolution used by task-producing surfaces, while keeping attribution separate:

- Prefer the real top-of-chain human originator when present.
- For an unattributed member-created autopilot run, use the autopilot creator **for authorization only** when the server-trusted task/issue lineage is verified.
- On child creation, bind the speaking task to the supplied parent issue before evaluating the fallback.
- Continue running `canInvokeAgent`; do not add an unconditional agent/admin bypass and do not use `accountable_user_id` as authorization.

Useful regression cases:

- verified lineage + creator owns/can invoke target + backlog child assignment -> `201`, zero queued worker tasks;
- creator lacks invoke rights -> `403`;
- missing `X-Task-ID`, actor/task mismatch, task bound to a different parent, or non-autopilot parent -> `403`;
- active-status creation should enqueue only after the same authority check succeeds.

## Related issues / PRs

- #5031 tracks the broader NULL-originator/private-worker problem.
- #5512 fixed the same authorization gap for autopilot `@mention` delegation, but issue create/update assignment still uses the originator-only path.

This was first observed through a downstream CLI, but the deterministic failure above is reproduced directly on unmodified upstream `main`; it is not caused by the downstream fork.

## Additional context

- Go: `go1.26.5 linux/amd64`
- PostgreSQL: fresh ephemeral `pgvector/pgvector:pg17`
- Migrations: all through `313_runtime_profile_add_dsh`, exit `0`
- Existing comment-delegation control: pass
- Assignment reproduction: fail, HTTP `403`
- Repository was restored clean after the temporary test; the PostgreSQL container was removed.

A sanitized full migration/test log is available if useful (428 lines, 18 KB); the relevant output is included above.

### PR DESCRIPTION
**Pull request by iiwish**
## Summary

- resolve the supplied parent issue before the child-assignment invoke gate when the target is an agent or squad
- use the existing server-verified autopilot delegation lineage as an authorization-only fallback when the speaking task has no human originator
- keep a real top-of-chain originator authoritative and continue enforcing `canInvokeAgent` for the selected private agent or squad leader
- leave issue/task attribution unchanged

## Security boundary

This does not add a general agent-to-agent or private-agent bypass. The fallback is available only when all existing lineage checks succeed:

- the request resolves to an agent actor with a trusted `X-Task-ID`
- the task belongs to that actor
- the task is bound to the exact supplied parent issue
- the parent has verified autopilot provenance in the same workspace
- the autopilot was created by a member
- that creator independently passes `canInvokeAgent` for the target

Missing, mismatched, cross-issue, non-autopilot, and unauthorized-creator cases continue to fail closed.

## Tests

The new end-to-end handler regression suite covers:

- verified backlog child assignment: `201`, correct parent/assignee, zero worker tasks
- verified active child assignment: `201`, exactly one unattributed worker task
- creator without invoke rights: `403`
- real originator without invoke rights takes precedence over the autopilot creator: `403`
- missing task lineage: `403`
- task/actor mismatch: `403`
- task bound to another issue: `403`
- non-autopilot parent: `403`

Validation completed on a fresh migrated `pgvector/pgvector:pg17` database:

- `go test ./internal/handler -run '^(TestCreateIssue_AutopilotLeaderAssignsPrivateWorker|TestCreateComment_AutopilotLeaderMentionEnqueuesPrivateWorker|TestAutopilotDelegationAuthority_LineageBinding|TestCreateIssue_AssignToPrivateAgentForbidsPlainMember|TestAssignAgent_DenialReasonNamesPermissionNotMode|TestCreateIssueRejectsCrossWorkspaceParent)$' -count=1 -v`
- `go test ./internal/handler -count=1`
- `bash scripts/test-go.sh --race`
- `pnpm typecheck`
- `pnpm exec turbo test --filter='!@multica/mobile' --filter='!@multica/desktop'`

The first full Go race run hit the existing `TestProbeAgentCLIsRequiresDshMulticaProfile` timing flake; its isolated race rerun passed, and a second complete `scripts/test-go.sh --race` run passed all packages.

Fixes #6941

### CODE REVIEW

**Review by multica-eve — CHANGES_REQUESTED** [review]
Thanks for the carefully scoped fix. The product behavior is right: a verified Autopilot delegation should be able to create a child assigned to a target that the Autopilot creator may invoke, without widening private-agent access or changing task attribution.

Please address the following before merge:

1. Rebase or merge the latest `main` and update the two new callers introduced by #7461. This PR adds a `delegationIssue` argument to `validateAssigneePair`, but the merged result still calls the old signature at `server/internal/handler/source_context.go:644` and `:757`. The actual merge tree fails to compile with `not enough arguments in call to h.validateAssigneePair`. Both member-driven source-context entry points should pass `nil`; they must not inherit Autopilot parent authority.

2. Please refactor `server/internal/handler/issue_autopilot_assignment_authority_test.go:11-42` to follow the repository's handler-test contract. The new helper open-codes `httptest.NewRecorder`, status checking, JSON decoding, and unchecked SQL cleanup. Keep the expected status at each product test with `testutil.Call(...).Want(...)`, and use the existing `dbfx` / checked cleanup patterns.

3. Because this changes an authorization and tenant boundary, please add a negative case that exercises the new assignee pre-load path with a cross-workspace parent: an agent or squad assignee plus an otherwise valid task header must still be rejected and must not create a row. The existing generic cross-workspace-parent test does not enter this new branch.

The permission design itself looks sound: a real human originator wins; the creator fallback is considered only for an unattributed request; task/actor, task/parent, Autopilot provenance, workspace, and target invocation permission remain fail-closed; attribution remains unchanged.

Validation performed:

- On the PR head, the targeted authorization suite and `go test ./internal/handler -count=1` pass.
- The real merge tree against current `main` fails to compile at the two call sites above.
- In a local merge simulation, adding only the two `nil` arguments makes the authorization regressions, source-context lifecycle test, and the full handler package pass.

Once the branch is current and these test updates are in place, I expect this to be ready to merge.

**Comment by iiwish** [comment]
@multica-eve Addressed all three review points in the latest push:

1. Merged current `main` (`39ddc82c9`) and updated both source-context callers to pass `nil`, so member-driven entry points cannot inherit Autopilot delegation authority.
2. Refactored the handler test helper to build requests only. Each product case now uses `testutil.Call(...).Want(...)`, typed JSON decoding, and `dbfx` query/cleanup helpers.
3. Added fail-closed cross-workspace-parent coverage for both agent and squad assignees with valid run headers, including assertions that no issue row is created.

Validation on a fresh PostgreSQL database with all migrations applied:
- targeted authorization and source-context suite under `-race`: pass
- full `go test ./internal/handler -count=1`: pass
- GitHub CI: all required checks pass

Latest head: `8e5486f61`. Please re-review when convenient.

**Review by multica-eve — APPROVED** [review]
Thank you for the careful update and for addressing all three review points. The source-context callers now stay outside the Autopilot fallback, the handler tests follow the shared fixture conventions, and the cross-workspace agent and squad cases prove the new permission boundary remains fail-closed.

I re-reviewed HEAD `8e5486f61` against the current `main`. The merge tree is clean, the targeted authorization/source-context suite passes under the race detector, the full handler suite passes on a freshly migrated database, and all required GitHub checks are green. This is ready to merge.
